### ISSUE TITLE
User Stories Epic

### ISSUE THREAD

**Issue by weswigham** [glimpseio/glacier#1]
Glimpse:

Users should be able to launch the application.
Users should be able to connect a data source.
Users should be able to connect an excel spreadsheet as a data source.
Users should be able to connect an csv file as a data source.
Users should be able to import a specific sheet from an excel spreadsheet.
Users should be able to pull a pallet of fields from a data source to choose which fields they would like to work with.
Users should be able to drag and drop fields into "aspects" for visual mapping (such as x, y, size, shape, or color - components which change the visualization).
Users should not have to specify an aggregation for a component by default (ie, there should be a default - ex, numbers should be averaged to produce a color if a numeric field is dropped into a color)
Users should be able to view a visual encoding which corresponds to a bar chart based on the aspects they configure.
Users should be able to view a visualization as they please, overriding the inferred visual encoding with their own (ie, swapping a bar to a point, line, area, or shape).
Users should observe line & area charts for temporally inferred fields.
Users should observe points by default for numeric fields on both axes.
Users should observe bars for inferred aggregates against categories.
Users should be able to configure additional encodings to layer upon existing ones. (Users should be able to add more visual dimensions to the visualization.)
Users should be able to add new fields to the fields pallet after import.
Users should be able to add annotations (titles, legends, axes descriptions) to a visualization using a WISYWIG editor.
Users should be able to save the visualization they design to a bundled html5 compliant file and saved to the desired location which contains all the information and code needed to display the visualization, data, and annotations configured as appropriate. This file should contain a static embedded SVG to provide a preview for headless browsers, search engines, and more.
Users should be able to export the visualization to a disparate bundle containing the same parts as the bundled html5 compliant file.
Users should have a live preview of their changes - each change the user makes should update the visualization in some way.
Users should be able to apply cosmetic improvements after configuring a visualization and should be able to reconfigure data sources of a visualization without needing to redo their cosmetic improvements.

Glacier:
API consumers expect it to be 'fast' - updates need to be produced in real time if input is provided in soft real time (ie, within a few multiples of a 20ms frame time on small data sets - it is OKAY to be slower with larger data sets).
API consumers expect to be able to run the library within node.
API consumers expect to be able to run the library within JavaScriptCore.
API consumers expect to be able to run the library within a chromium runtime. 
API consumers expect to run the library in ES5 or greater compliant runtimes.
API consumers expect to interact with the API in an event based manner.
API consumers expect to be able to cancel slow function calls or otherwise monitor the performance of calls into the API.
API consumers expect the program to be well-behaved with respect to cancellation tokens.
API consumers should expect to be able to cancel individual updates.
API consumers expect to be able to serialize database connections.
API consumers expect to be able to serialize cross-database queries and their joins. (Maybe not specific to glacier? Maybe more in glean?)
API consumers expect to be able to store state inside glacier and listen on events from glacier for updates from other components.

**Comment by colinferris** [comment]
Moved to [wiki](https://github.com/glimpseio/glacier/wiki/User-Stories).
