### ISSUE TITLE
API consumers expect it to be 'fast' - updates need to be produced in real time if input is provided in soft real time (ie, within a few multiples of a 20ms frame time on small data sets - it is OKAY to be slower with larger data sets).

### ISSUE THREAD

**Issue by colinferris** [glimpseio/glacier#10]

**Comment by weswigham** [comment]
I'm not 100% on this task being 'completable'. I think its just a metric we'll have to keep in mind moving forward. Towards that end, it could make sense to include a tined stress test in the test suite to ensure we don't exceed the limit specified here. So maybe the associated code task should be "Continuously test performance for soft realtime use".

**Comment by colinferris** [comment]
Moved to [wiki](https://github.com/glimpseio/glacier/wiki/User-Stories).
