### ISSUE TITLE
Comparison predicates

### ISSUE THREAD

**Issue by mprudhom** [glimpseio/glacier#31]
Users should be able to construct comparison predicates for data filtering. For example, comparing the field "fld" to 123 might be expressed in the model as:

```json
{
  "compare": "eq",
  "lhs": { "field": "fld" },
  "rhs": { "const": 123 }
}
```

This will probably yield the SQL:

```sql
SELECT ... FROM ... WHERE "fld" = 123
```

In addition to "equal", other valid comparisons operators should be "ne" (not equal), "gt" (greater than), "lt" (less than), "gte" (greater than or equal), "lte" (less than or equal).

**Comment by weswigham** [comment]
Implemented by #87.
