### ISSUE TITLE
Compound predicates

### ISSUE THREAD

**Issue by mprudhom** [glimpseio/glacier#32]
Users should be able to construct compound predicates for data filtering, such as AND, OR, and NOT queries. Compound predicates must be able to embed comparison predicates (as specified in issue #31) and other compound predicates.

For example, comparing the field "numfld" as greater than 123 and "strfld" as equal to "FOO" might be expressed in the model as:

```json
{
  "compound": "and",
  "operations": [
    {
        "compare": "gt",
        "lhs": { "field": "numfld" },
        "rhs": { "const": 123 }
    },
    {
        "compare": "eq",
        "lhs": { "field": "strfld" },
        "rhs": { "const": "FOO" }
    }
  ]
}

```

This will probably yield the SQL:

```sql
SELECT ... FROM ... WHERE "numfld" > 123 AND "strfld" = 'FOO'
```

**Comment by weswigham** [comment]
Implemented by #87 (though exactly not as described).
